### ISSUE TITLE
In whose collection is Archive.org stored?

### ISSUE THREAD

**Issue by iamharshkumar97** [pirate/ArchiveBox#128]
If possible can I add it to my own collection?

**Comment by pirate** [comment]
I'm not sure I understand the question? Archive.org is a non-profit archiving organization that created the original Wayback Machine.  ArchiveBox submits urls to them for archiving because their archiving system is robust and works well for many types of sites, and the redundancy is nice in case ArchiveBox fails or the data locally is lost for any reason.

**Comment by iamharshkumar97** [comment]
Oh! I was a bit confused. I was thinking that all the links submitted are attributed to an account. 

Another question. I am thinking to putting ArchiveBox on a VPS. I save all my bookmarks at http://pinboard.in. How can I automatically get new bookmarks?

**Comment by pirate** [comment]
```bash
curl https://user:passwd@api.pinboard.in/v1/posts/all > output/downloads/pinboard.html

./archive output/downloads/pinboard.html
```

That should do the trick.
