### ISSUE TITLE
Behavior: Merge two archives from two separate instances (already supported in v0.4)

### ISSUE THREAD

**Issue by totalizator** [pirate/ArchiveBox#248]
Is this possible to merge two archives from two separate instances of ArchiveBox? 

This would allow me to dump the archive periodically to some other place when running out of free disk space etc.

**Comment by pirate** [comment]
This is easy with v0.4.0, just copy all the archive folders from one into the other.  Unfortunately I cant release it publicly yet due to some needed security fixes that I haven't gotten around, and probably wont have time to fix for at least a month or so.

If you can wait until then, great! Otherwise let me know and I'll walk you through the process on the older version.

**Comment by totalizator** [comment]
Amazing! Thank you so much.

I will start with the most recent version then.
