### ISSUE TITLE
Configuration: getting start on docker image leads to error

### ISSUE THREAD

**Issue by metroroland** [pirate/ArchiveBox#260]
Executing the docker image :
 `echo 'https://google.com' | docker run -i -v /archiveBox:/data nikisweeting/archivebox`

Lead to the following error
`standard_init_linux.go:211: exec user process caused "exec format error"`

Probably a duplicate for  #243 and my host is an arm64 SBC

    >root@pine64:~#  lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 18.04.3 LTS
    Release:        18.04
    Codename:       bionic
    >root@pine64:~# docker --version
    Docker version 19.03.1, build 74b1e89

Thanks for your time.

Edit, i download the ubuntu distribution ftom armbian.com

**Comment by cdvv7788** [comment]
@metroroland is this still happening to you with the latest image?

**Comment by pirate** [comment]
I'm going to close this for now since the `django` branch has likely fixed this. If you still encounter problems feel free to comment back here and I'll reopen the ticket.

```bash
git checkout django
git pull
docker build . -t archivebox
docker run -v $PWD/output:/data archivebox init
```

**Comment by bxkx** [comment]
I'm still experiencing this with RPi 4 running DietPi, following the docker-compose instructions. 

I changed the version in the docker-compose.yaml to 3.6 though, as 3.7 gives me "ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version." Even though I have Docker version 19.03.12 which supposedly supports.

I guess the Docker image just doesn't support ARM?
