### ISSUE TITLE
Bugfix: archivebox.io "Demo" link broken (Error 1016)

### ISSUE THREAD

**Issue by ItsExtra** [pirate/ArchiveBox#280]
#### Describe the bug

archivebox.io "Demo" link broken (Error 1016)

#### Steps to reproduce

1. go to archivebox.io 
2. Click "Demo" in top navigation

#### Screenshots or log output

> Error 1016 Ray ID: 524b3e4c09edc867 • 2019-10-12 18:47:37 UTC
> Origin DNS error
> What happened?
> 
> You've requested a page on a website (archive.sweeting.me) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (archive.sweeting.me).
> What can I do?
> 
> If you are a visitor of this website:
> Please try again in a few minutes.
> 
> If you are the owner of this website:
> Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. Additional troubleshooting information here.
> 
> Cloudflare Ray ID: 524b3e4c09edc867 • Your IP: 185.65.134.175 • Performance & security by Cloudflare

![Screen Shot 2019-10-12 at 2 45 03 PM](https://user-images.githubusercontent.com/54250414/66706349-d896ab00-ed20-11e9-8997-07b0aeee3138.png)

Maybe it'll resolve spontaneously but I won't remember to check again so thought I'd report it while it's in my mind.

**Comment by dataarchivist** [comment]
Still not working. Its sad for new users who want to test it before installing. May better delete the link and just use screenshots.

**Comment by pirate** [comment]
Duplicate: https://github.com/pirate/ArchiveBox/issues/231

**Comment by UmutAlihan** [comment]
this error also shown on archiving many  sites ... Unfortunately it blocks many archived content and decreases the efficiency and promised capabilities of Archivebox ://

**Comment by pirate** [comment]
@UmutAlihan this error has nothing to do with Archivebox the software, it's just a generic cloudflare warning shown when *any* cloudflare-hosted site points to a broken domain.

The original ticket is about the demo server being down, which it often is, and is not related to content you're trying to archive failing.

**Comment by UmutAlihan** [comment]
> @UmutAlihan this error has nothing to do with Archivebox the software, it's just a generic cloudflare warning shown when _any_ cloudflare-hosted site points to a broken domain.
> 
> The original ticket is about the demo server being down, which it often is, and is not related to content you're trying to archive failing.

My only question would be; are you sure that such cloudflare warning points to a broken domain? Because when I try to reach URL manually, the site shows up and online. However once archivebox tries to archive the site the error on the pic only archived.

I think the issue about the archiving error msg from cloudflare instead of site itself might be anything to do with the failing to avoid bot detection services (such as browser fingerprinting) from cloudflare, which provides DNS service to the sites we try to archive..

However it would be very much appreciated to avoid cognitive dissonance and acknowledge the feedback provided with positive impact intents and hopefully further develop a fully functional great personal archiver of all times.

Cheers,

![image](https://user-images.githubusercontent.com/16688836/140591645-694a78c3-fa81-4d97-bee5-d3bed02bedc6.png)
