### ISSUE TITLE
ArchiveBox shows the wrong output path when run from a different directory than the binary

### ISSUE THREAD

**Issue by Julian** [pirate/ArchiveBox#283]
When running e.g. `cd Desktop; /path/to/archivebox/archive foo.html`, archivebox shows:

```
[X] [2019-10-13 19:18:51] Downloading paused on link 1563727241.19 (37/2834)
    To view your archive, open: output/index.html
    Continue where you left off by running:
        archive 1563727241.19
```

when exiting the process, but `output` there is actually seemingly by default relative to the archive binary, not the working directory.

#### Software versions

 - OS: macos
 - ArchiveBox version:        eb641b3
 - Python version:            pypy3 (3.6.1)

**Comment by pirate** [comment]
Thanks for reporting! The whole model of where the data folder is stored changes in `>=v0.4`.  `archivebox` becomes a command that can be globally installed on the whole system with `pip install archivebox`, then whatever folder it's run in becomes the data folder.

e.g.
```bash
mkdir ~/archivebox && cd ~/archivebox
archivebox init
...
```

The v0.4 release is blocked by a few security issues, but once it lands you can `pip install` and you'll find this issue is fixed.
