### ISSUE TITLE
Question: Changing date to human readable format

### ISSUE THREAD

**Issue by dataarchivist** [pirate/ArchiveBox#295]
I may miss the line, but it is possible to change "the number" before an url, to something more like
20191119-213530? For the folder structure and the index page.

**Comment by pirate** [comment]
Not currently, the plan is to move away from timestamps entirely and use hashes instead: https://github.com/pirate/ArchiveBox/issues/74

I'm going to close this for now, because while we may add support for other timestamp formats in the url to get snapshots in the future, it's not going to be until after v0.4 has been released and used for a while.
